# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Dewan hasan
  email: g00410156@atu.ie
description: "Digital Rain Project Blog."

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [The title of your site]
description: [A short description of your site's purpose]

